services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Keep the service public so it stays fetchable by id / injectable.
    jonasarts\Bundle\GoogleAuthenticatorBundle\Authenticator\GoogleAuthenticator:
        public: true
